name: Build Ionic App for iOS bank muscat

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Xcode
      run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          xcodebuild -version

    - name: Decode and install certificate
      run: |
        echo "${{ secrets.IOS_CERTIFICATE }}" | base64 -d > certificate.p12
        security create-keychain -p actions build.keychain
        security default-keychain -s build.keychain
        security import certificate.p12 -k build.keychain -P "123456789" -T /usr/bin/codesign
        security set-keychain-settings build.keychain

    - name: Decode provisioning profile
      run: |
        echo "${{ secrets.IOS_PROVISIONING_PROFILE }}" | base64 -d > profile.mobileprovision
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

    - name: Build and Archive App
      run: |
        cd BOD
        xcodebuild -workspace BOD.xcworkspace -scheme BOD -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        xcodebuild -workspace BOD.xcworkspace -scheme BOD -configuration Release -archivePath $PWD/build/BOD.xcarchive archive
        xcodebuild -exportArchive -archivePath $PWD/build/BOD.xcarchive -exportPath $PWD/build -exportOptionsPlist $PWD/exportOptions.plist

    - name: Upload iOS App
      uses: actions/upload-artifact@v2
      with:
        name: BodApp.ipa
        path: BOD/build/BodApp.ipa
