name: Build Ionic App for iOS bank muscat

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Xcode
      run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          xcodebuild -version

    - name: Decode and install certificate
      run: |
        echo "${{ secrets.IOS_CERTIFICATE }}" | base64 -d > certificate.p12
        security create-keychain -p actions build.keychain
        security default-keychain -s build.keychain
        security import certificate.p12 -k build.keychain -P "123456789" -T /usr/bin/codesign
        security set-keychain-settings build.keychain

    - name: Decode provisioning profile
      run: |
        echo "${{ secrets.IOS_PROVISIONING_PROFILE }}" | base64 -d > profile.mobileprovision
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

    - name: Build iOS App
      run: npx ionic cordova build ios --prod --release

    - name: Archive iOS App
      run: |
        cd platforms/ios/build/device
        zip -r ${{ github.workspace }}/BodApp.ipa *.app

    - name: Upload iOS App
      uses: actions/upload-artifact@v2
      with:
        name: BodApp.ipa
        path: BodApp.ipa